<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Magento Core Team <Ced_MagentoCoreTeam@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<div class="vendor-cms">
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<div class="col-lg-12">
	    <h1 class="icon-head head-products page-header cms-page-wrap"><?php echo Mage::helper('cscmspage')->__('Manage Vendor CMS Page') ?>
	       <div style="float:right" class="content-buttons-placeholder" style="width: 0px; height: 14px;">
		    	<p class="content-buttons form-buttons">
		    	<?php echo $this->getButtonsHtml() ?>
		    	</p>
		    </div>
	     </h1>
	    <div style="clear:both;"></div>     
	</div>

	<?php echo $this->getChildHtml('store_switcher');?>
	<div class="col-md-12" style="margin-top: 10px;">
		<div class="panel panel-default">
			<div class="content-header panel-heading col-md-12 uptransform">
				<h3 class="icon-head head-products col-md-6">Manage Cms Page</h3>
			</div>
		    	<?php echo $this->getGridHtml() ?>
		</div>
	</div>	
	<div id="loading-mask" style="display:none">
	    <p class="loader" id="loading_mask_loader"><img src="<?php echo $this->getSkinUrl('images/ced/cscmspage/ajax-loader-tr.gif') ?>" alt="<?php echo Mage::helper('cscmspage')->__('Loading...') ?>"/></p>
	</div> 
	<script type="text/javascript">
		var BLANK_URL = '<?php echo $this->getJsUrl() ?>blank.html';
		var BLANK_IMG = '<?php echo $this->getJsUrl() ?>spacer.gif';
		var BASE_URL = '<?php echo Mage::getUrl('*') ?>';
		var SKIN_URL = '<?php echo $this->getSkinUrl() ?>';
		var FORM_KEY = '<?php echo $this->getFormKey() ?>';
		//alert(BLANK_URL+'=>'+BLANK_IMG+'=>'+BASE_URL+'=>'+SKIN_URL+'=>'+FORM_KEY);
		
	</script>
	<div style="clear:both"></div>
</div>
