<?php

/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the Academic Free License (AFL 3.0)
  * You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
  * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/afl-3.0.php
  *
  * @category    Ced
  * @package     Ced_CsCmsPage
  * @author      CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
  */
 ?>
<?php if(Mage::helper('cscmspage')->getApprovalVendorCms()){?>
	<div class="notification-global">	
		<strong class="label"><span class="critical"><strong><?php echo Mage::helper('cscmspage')->getApprovalVendorCms(); ?></strong></span> <?php echo Mage::helper('cscmspage')->__('Vendor CMS Approval Request for Vendor(s).'); ?></strong>
		<?php echo Mage::helper('cscmspage')->__('Approve Vendor CMS from'); ?> <a href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/adminhtml_vendorcms/"); ?>"><?php echo Mage::helper('cscmspage')->__('Manage Vendors CMS').' '.Mage::helper('cscmspage')->__('Panel'); ?></a>.
	</div>
<?php } ?>	

<?php if(Mage::helper('cscmspage')->getApprovalVendorBlock()){ ?>
		<div class="notification-global">	
			<strong class="label"><span class="critical"><strong><?php echo Mage::helper('cscmspage')->getApprovalVendorBlock(); ?></strong></span> <?php echo Mage::helper('cscmspage')->__('Vendor Static Block Approval Request for Vendor(s).'); ?></strong>
			<?php echo Mage::helper('cscmspage')->__('Approve Vendor Static Block from'); ?> <a href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/adminhtml_vendorblock/"); ?>"><?php echo Mage::helper('cscmspage')->__('Manage Vendors CMS Block').' '.Mage::helper('cscmspage')->__('Panel'); ?></a>.
		</div>
<?php }?>

