<?php 
 /**
  * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the Academic Free License (AFL 3.0)
  * You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
  * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/afl-3.0.php
  *
  * @category    Ced
  * @package     Ced_CsDeal
  * @author      CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
  */

 
?>
<div class="vendor-dashboard">
	<div class="row">
		<div class="col-md-12" style="margin-top:10px;">
			</div>
			<div class="panel panel-default">
			</div>	
			<div class="panel panel-default">
				<div class="panel-heading col-md-12 uptransform" style="line-height:31px;font-weight:bold;padding:4px 15px;font-size:17px;">
					<?php echo $this->__('Create Deals'); ?>
					<div class="buttons-set col-md-6 buttons_scb" style="float:right;text-align:right;margin-right:2px;">	
						<button style="" onclick="dealback()" class="scalable btn-warning" type="button" id="deal_createback"><span><?php echo $this->__('Back'); ?></span></button>
						<button style="" onclick="save()" class="scalable btn-success " type="button" id="deal_createsave"><span><?php echo $this->__('Create Deal'); ?></span></button>
					</div>
					<div style="clear:both"></div>
				</div>
				<script type="text/javascript">
					 function save(){
                                deal_form.submit($('deal_form').action);
                            }
                            function dealback(){
                                document.location.href='<?php echo Mage::getUrl("csdeal/deal/create"); ?>';
                            }
				</script>
				<div style="clear:both"></div>
				<div class="panel-body">
<div class="vendor panel" style="padding:2%">
    <div id="deal-wrapper" class="deal-wrapper" >
	<form id="deal_form" action="<?php echo Mage::getUrl('csdeal/deal/save'); ?>" method="post">
	  <div class="fieldset">
		<ul class="form-list">
			<li class="fields">
				<label class="required" for="date_from"><?php echo $this->__('Product Id'); ?></label><em>*</em>
                <div class="clear:both"></div>
				<div class="input-box">
                <input type="text" style="width: 120px;" class="input-text required-entry" readonly="true" value="<?php echo $this->getProductId(); ?>" id="product_id" name="product_id"/>
                </div>
                <input type="hidden" value="<?php echo $this->_getSession()->getVendorId(); ?>" id="vendor_id" name="vendor_id"/>
			</li>
			<li class="fields">
				<label class="required" for="deal_product_name"><?php echo $this->__('Product Name'); ?></label><em>*</em>
                <div class="clear:both"></div>
				<div class="input-box">
              
                <input type="text" style="width: 120px;" class="input-text required-entry" readonly="readonly" value="<?php echo $this->getProductName(); ?>" id="deal_product_name" name="deal_product_name"/>
               
                </div>
			</li>
			
			<li class="fields">
				<label class="required" for="enable_status"><?php echo $this->__('Deal Status'); ?></label><em>*</em>
				 <div class="clear:both"></div>
				<div class="input-box">
					<select id="enable_status" class="validate-select required-entry" name="status">
					<?php
					$status=Mage::getModel('csdeal/status')->getOptionArray();
					foreach ($status as $key => $value) {
						?>
						<option value="<?php echo $key; ?>" ><?php echo $this_>__($value); ?></option>	
						<?php 
					}
					 ?>
					</select>
				</div>
			</li>
			<li class="fields">
				<label class="required" for="deal_price"><?php echo $this->__('Deal Price'); ?></label><em>*</em>
                <div class="clear:both"></div>
				<div class="input-box">
              
                <input type="text" style="width: 120px;" class="input-text required-entry validate-number"  value="" id="deal_price" name="deal_price"/>
               
                </div>
			</li>
			<li class="fields">
				<label class="required" for="date_from"><?php echo $this->__('Deal From'); ?></label><em>*</em>
				 <div class="clear:both"></div>
				<div class="input-box">
                 
                <input type="text" style="width: 120px;" class="input-text required-entry" readonly="readonly" value="" id="start_date" name="start_date"/>
               
                </div>
                <img style="" title="Select Date" id="date_select_from"  class="v-middle" alt="" src="<?php echo $this->getSkinUrl("images/calendar.gif");?> "/>
                <div class="clear:both"></div>
			</li>
			<li class="fields">
				<label class="required" for="date_to"><?php echo $this->__('Deal To'); ?></label><em>*</em>
				 <div class="clear:both"></div>
				<div class="input-box">
				
                <input type="text" style="width: 120px;" class="input-text required-entry" readonly="readonly" value="" id="end_date" name="end_date"/>
                
    		    </div>
    		    <img style="" title="Select Date" id="date_select_to" class="v-middle" alt="" src="<?php echo $this->getSkinUrl("images/calendar.gif");?> "/>
				<div class="clear:both"></div>
			</li>
			<li class="fields">
				<label class="required"><?php echo $this->__('Day(s)'); ?></label><em>*</em>
				 <div class="clear:both"></div>
				<div class="input-box required-entry">
					<select id="days" class="validate-select" name="days" onchange="showField(this.value);" >
						<option value="1"><?php echo $this->__('All Day(s)'); ?></option>
						<option value="0"><?php echo $this->__('Specific Day(s)'); ?></option>
					</select>			
				</div>
				<div id="specific-days" style="display:none" class="input-box required-entry">
					<select id="specificdays" class="validate-select  select multiselect" name="specificdays[]" multiple="multiple" >
						<option value="sun"><?php echo $this->__('Sunday'); ?></option>
						<option value="mon"><?php echo $this->__('Monday'); ?></option>
						<option value="tue"><?php echo $this->__('Tuesday'); ?></option>
						<option value="wed"><?php echo $this->__('Wednessday'); ?></option>
						<option value="thu"><?php echo $this->__('Thursday'); ?></option>
						<option value="fri"><?php echo $this->__('Friday'); ?></option>
						<option value="sat"><?php echo $this->__('Saturday'); ?></option>
					</select>			
				</div>
			</li>
		</ul>
		
	<button class="btn btn-primary button"><span><?php echo $this->__('Create Deal') ?></span></button>
	</div>
</form>
</div>
</div>
</div>
</div>
</div>
</div>
<script type="text/javascript">
document.getElementById('specificdays').disabled = true;
function showField(data){
	if(data==0){
	document.getElementById('specific-days').style.display="block";
	document.getElementById('specificdays').disabled = false;
	
	}else{
		document.getElementById('specific-days').style.display="none";
		document.getElementById('specificdays').disabled = true;

	}
}
var deal_form = new VarienForm('deal_form','<?php echo $this->getValidationUrl() ?>');
  Calendar.setup({
      inputField: "start_date",
      ifFormat: "%Y-%m-%e %H:%M:%S",
      showsTime: true,
      button: "date_select_from",
      align: "Bl",
      singleClick : true
  });
  Calendar.setup({
      inputField: "end_date",
      ifFormat: "%Y-%m-%e %H:%M:%S",
      showsTime: true,
      button: "date_select_to",
      align: "Bl",
      singleClick : true
  });
</script>
