<?php
 /**
  * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the Academic Free License (AFL 3.0)
  * You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
  * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/afl-3.0.php
  *
  * @category    Ced
  * @package     Ced_CsDeal
  * @author      CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
  */
?>

	<div id="messages">
		<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	</div>
	<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="edit_form" enctype="multipart/form-data">
		<?php echo $this->getBlockHtml('formkey'); ?>
		<div class="row">
			<div class="col-md-12" style="margin-top: 10px;">
				<div class="panel panel-default">
					<div class="content-header panel-heading col-md-12 uptransform">
						<div style="font-size:17px;line-height:31px; margin-top:6px;" class="col-md-6 panel_product_heading">
							<?php echo $this->getHeaderHtml()?>
						</div>
						<div style="text-align:right;" class="buttons-set col-md-6 buttons_scb">	
						<?php echo $this->getFormInitScripts()?>	
							<?php echo $this->getButtonsHtml() ?>
						</div>
					</div>
					<?php echo $this->getFormScripts()?>
					<?php echo $this->getChildHtml('deal_tabs'); ?>
				</div>
			</div>
		</div>
	</form>
