<?php 
 /**
  * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the Academic Free License (AFL 3.0)
  * You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
  * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/afl-3.0.php
  *
  * @category    Ced
  * @package     Ced_CsDeal
  * @author      CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
  */

?>

<div id="messages">
	 <?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
 </div>
<div class="vendor-dashboard">
	<div class="row">
		<div class="col-md-12" style="margin-top:10px;">
			<div class="panel panel-default">
				<div class="panel-heading col-md-12 uptransform" style="line-height:31px;font-weight:bold;padding:4px 15px;font-size:17px;">
					<?php echo Mage::helper('csdeal')->__('Deal Setting'); ?>
				</div>
				<div style="clear:both"></div>
				<div class="panel-body">
					 <div id="deal-setting-wrapper" class="deal-setting-wrapper" >
						<form id="deal_form" action="<?php echo Mage::getUrl('csdeal/setting/save'); ?>" method="post">
						<?php $vendorid=Mage::getModel('customer/session')->getVendorId(); 
							$setting=Mage::getModel('csdeal/dealsetting')->getCollection()->addFieldToFilter('vendor_id',$vendorid)->getFirstItem();
						?>
						<div class="fieldset">
							<ul class="form-list">
								<li class="fields">
								<label  for="date_from"><?php echo $this->__('Show Deals'); ?></label><em>*</em>
					                <div class="clear:both"></div>
									<div class="input-box">
					                <select  class="input-text required-entry" id="deal_enable" name="status">
					                <option value="enable" <?php if($setting->getStatus()=='enable') echo 'selected'; ?> >Enable</option>
					                <option value="disable" <?php if($setting->getStatus()=='disable') echo 'selected'; ?> >Disable</option>
					                </select>
					                </div>
					                <input type="hidden" value="<?php echo Mage::getModel('customer/session')->getVendorId(); ?>" id="vendor_id" name="vendor_id"/>
					                <input type="hidden" value="<?php echo $setting->getId(); ?>" id="setting_id" name="setting_id"/>
								</li>
								<li class="fields">
									<label  for="deal_listing"><?php echo $this->__('Show Deal'); ?></label><em>*</em>
					                <div class="clear:both"></div>
									<div class="input-box">
					                <select class="input-text required-entry"  value="<?php ?>" id="deal_listing" name="deal_list">
					                <?php 
					                $list= Mage::getModel('csdeal/list')->toOptionArray();
					                foreach ($list as $key => $value) {
					                	?>
					                	 <option value="<?php echo $key; ?>" <?php if($setting->getDealList()==$key) echo 'selected'; ?> ><?php echo $value; ?></option>

					                <?php 
					                } ?>
					               

					                </select>
					               
					                </div>
								</li>
								<li class="fields">
									<label  for="deal_product_name"><?php echo $this->__('Show Timer'); ?></label><em>*</em>
					                <div class="clear:both"></div>
									<div class="input-box">
					              
					                <select class="input-text required-entry"  value="<?php ?>" id="timer_listing" name="timer_list">
					                <?php 
					                $list= Mage::getModel('csdeal/list')->toOptionArray();
					                foreach ($list as $key => $value) {
					                	?>
					                	 <option value="<?php echo $key; ?>" <?php if($setting->getTimerList()==$key) echo 'selected'; ?> ><?php echo $value; ?></option>

					                <?php 
					                } ?>
					                </select>
					                </div>
								</li>
								<li class="fields">
									<label  for="deal_message"><?php echo $this->__('Deal Message'); ?></label><em>*</em>
					                <div class="clear:both"></div>
									<div class="input-box">
					              
					                <input type="text" class="input-text required-entry"  value="<?php echo $setting->getDealMessage() ?>" id="deal_message" name="deal_message"/>
					               
					                </div>
								</li>
							</ul>
						<button class="btn btn-primary button"><span><?php echo $this->__('Submit') ?></span></button>	
						</div>
					</form>
				</div>					
				</div>
			</div>
		</div>
	</div>
</div>	
				
