<?php
/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the Academic Free License (AFL 3.0)
  * You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
  * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/afl-3.0.php
  *
  * @category    Ced
  * @package     Ced_CsProduct
  * @author   CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
  */
?>
<?php echo $this->helper('adminhtml/media_js')->getTranslatorScript() ?>

<div id="<?php echo $this->getHtmlId() ?>" class="uploader">
    <div class="buttons">
        <div id="<?php echo $this->getHtmlId() ?>-install-flash" style="display:none">
            <?php echo Mage::helper('media')->__('This content requires last version of Adobe Flash Player. <a href="%s">Get Flash</a>', 'http://www.adobe.com/go/getflash/') ?>
        </div>
    </div>
    <div class="clear"></div>
    <div class="no-display" id="<?php echo $this->getHtmlId() ?>-template">
        <div id="{{id}}" class="file-row">
        <span class="file-info">{{name}} ({{size}})</span>
        <span class="delete-button"><?php echo $this->getDeleteButtonHtml() ?></span>
        <span class="progress-text"></span>
        <div class="clear"></div>
        </div>
    </div>
    <div class="no-display" id="<?php echo $this->getHtmlId() ?>-template-progress">
        {{percent}}% {{uploaded}} / {{total}}
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
maxUploadFileSizeInBytes = <?php echo $this->getDataMaxSizeInBytes() ?>;
maxUploadFileSize = '<?php echo $this->getDataMaxSize() ?>';

<?php echo $this->getJsObjectName() ?> = new Flex.Uploader('<?php echo $this->getHtmlId() ?>', '<?php echo $this->getSkinUrl('images/ced/csproduct/media/uploader.swf') ?>', <?php echo $this->getConfigJson() ?>);
<?php echo $this->getJsObjectName() ?>.onFilesComplete = function(completedFiles){
    completedFiles.each(function(file){
        <?php echo $this->getJsObjectName() ?>.removeFile(file.id);
    });
    MediabrowserInstance.handleUploadComplete();
}
// hide flash buttons
if ($('<?php echo $this->getHtmlId() ?>-flash') != undefined) {
    $('<?php echo $this->getHtmlId() ?>-flash').setStyle({float:'left'});
}
//]]>
</script>
