<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Magento Core Team <magentocoreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 
?>
<?php
$vorder = Mage::registry('current_vorder');
$_order  = $this->getOrder();
$_source = $this->getSource();
$_fullInfo  = $this->getFullTaxInfo();
?>


<div class="order-totals"><table width="100%" cellspacing="0">
    <colgroup><col>
    <col width="1">
            </colgroup><tfoot>
        <tr class="0">
            <td class="label">
                <?php echo  $this->helper('csmarketplace')->__('SubTotal')?>
            </td>
            <td class="emph">
                <strong><span class="price"><?php echo  Mage::app()->getLocale()->currency($vorder->getCurrency())->toCurrency($vorder->getPurchaseGrandTotal()); ?></span></strong>
            </td>
        </tr>
		<?php if(Mage::helper('csorder')->canShowShipmentBlock($vorder)){ ?>
		<tr class="1">
            <td class="label">
                <?php echo  $this->helper('csmarketplace')->__('Shipping & Handling')?>
            </td>
            <td class="emph">
                <strong><span class="price"><?php echo  Mage::app()->getLocale()->currency($vorder->getCurrency())->toCurrency($vorder->getBaseShippingAmount()); ?></span></strong>
            </td>
        </tr>
		<?php } ?>
		
		<tr class="2">
            <td class="label">
                <strong><?php echo  $this->helper('csmarketplace')->__('Grand Total (Earned)')?></strong>
            </td>
            <td class="emph">
                <strong><span class="price"><?php echo  Mage::app()->getLocale()->currency($vorder->getCurrency())->toCurrency($vorder->getOrderTotal()); ?></span></strong>
            </td>
        </tr>
		
		
		
        <tr class="3">
            <td class="label">
                <strong> <?php echo  $this->helper('csmarketplace')->__('Commission Fee')?></strong>
            </td>
            <td class="emph">
                <strong><span class="price">-<?php echo Mage::app()->getLocale()->currency($vorder->getCurrency())->toCurrency($vorder->getShopCommissionFee()); ?></span></strong>
            </td>
        </tr>
                            <tr class="2">
            <td class="label">
                <strong><?php echo  $this->helper('csmarketplace')->__('Net Earned')?></strong>
            </td>
            <td class="emph">
                <strong><span class="price"><?php echo Mage::app()->getLocale()->currency($vorder->getCurrency())->toCurrency($vorder->getOrderTotal()-$vorder->getShopCommissionFee()); ?></span></strong>
            </td>
        </tr>
      </tfoot>
    </table>
</div>
