<?php 
/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the Academic Free License (AFL 3.0)
  * You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
  * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/afl-3.0.php
  *
  * @category    Ced
  * @package     Ced_CsProAssign
  * @author      CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
  */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <div style="float: right;"><?php echo $this->getButtonsHtml() ?></div>
        <h4 class="fieldset-legend <?php echo ($this->getHeaderCssClass()) ? $this->getHeaderCssClass().' icon-head' : '' ?>"><?php echo $this->getHeaderText() ?></h4>
    </div>
    <div class="fieldset">
		<?php echo $this->getLayout()->createBlock('Ced_CsProAssign_Block_Adminhtml_Addpro_Search_Grid')->toHtml(); ?>
    </div>
</div>
<script type="text/javascript">
	function addProduct() {
		var ids = document.getElementsByName("csassign_product_id");
		var parray= new Array();
		  var cboxes = document.getElementsByName('csassign_product_id');
		    var len = cboxes.length;
		    for (var i=0; i<len; i++) {
		        if(cboxes[i].checked){
		        if(cboxes[i].value!='on')	
		        parray.push(cboxes[i].value);
		        }
		    }
		var csloader = new varienLoader();
		if(parray.toString().length>0){
			new Ajax.Request('<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/adminhtml_assign/addProducts" )?>', {
			  parameters: { 'vendor_id':'<?php echo $this->getRequest()->getParam("vendor_id"); ?>','product_ids': parray.toString() },
			  onComplete: function(transport) {
			  	if(transport.responseText!='success'){
			  		document.getElementById("messages").innerHTML='<ul class="messages"><li class="error-msg"><ul><li><span>'+transport.responseText+'</span></li></ul></li></ul>';
			  	}else{
			  		document.getElementById("messages").innerHTML='<ul class="messages"><li class="success-msg"><ul><li><span> Product(s) assign successfully</span></li></ul></li></ul>'
			  	}
							document.getElementById("csmarketplace_add_more").style.display = "";
							document.getElementById("order-search").style.display = "none";
							catalog_category_productsJsObject.resetFilter();
							vproductGrids_<?php echo Mage::app()->getRequest()->getParam('vendor_id'); ?>JsObject.resetFilter();
						},
			});

		}else{
			document.getElementById("messages").innerHTML='<ul class="messages"><li class="error-msg"><ul><li><span>Please select Product to assign</span></li></ul></li></ul>';
		}
		
	}
</script>
