<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    design
 * @package     default_default
 * @author 		CedCommerce Magento Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php  $_order = $this->getOrder();
$vorder = Mage::registry('current_vorder');
?>
<?php 
if($this->getRequest()->getActionName()!="print"){ ?>
<button style="line-height: 1.2em;float:right" type="button" onclick="window.open('<?php echo $this->getPrintUrl($vorder); ?>')" title="<?php echo $this->__('Print Order') ?>" class="button btn btn-warning uptransform"><span><span><?php echo $this->__('Print Order') ?></span></span></button>
<?php } ?>
<?php 
if($this->canCreateShipment()){ ?>
<button style="line-height: 1.2em;float:right" type="button" onclick="window.open('<?php echo $this->getPrintUrl($vorder); ?>')" title="<?php echo $this->__('Ship') ?>" class="button btn btn-warning uptransform"><span><span><?php echo $this->__('Ship') ?></span></span></button>
<?php } ?>
<?php echo $this->getChildHtml(); ?>
