<?php
/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the Academic Free License (AFL 3.0)
  * You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
  * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/afl-3.0.php
  *
  * @category    Ced
  * @package     Ced_CsProduct
  * @author   CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
  */
?>
<div id="messages"></div>
 <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="content-header">
    <h3 class="icon-head head-products"><?php echo Mage::helper('catalog')->__('Manage Products') ?></h3>
    <div class="content-buttons-placeholder" style="width: 0px; height: 14px;">
    	<p class="content-buttons form-buttons" style="">
    	<?php echo $this->getButtonsHtml() ?>
    	</p>
    </div>
           
</div>
<?php echo $this->getChildHtml('store_switcher');?>
<div>
    <?php echo $this->getGridHtml() ?>
</div>
<script>
var BLANK_URL = '<?php echo $this->getJsUrl() ?>blank.html';
var BLANK_IMG = '<?php echo $this->getJsUrl() ?>spacer.gif';
var BASE_URL = '<?php echo $this->getUrl('*') ?>';
var SKIN_URL = '<?php echo $this->getSkinUrl() ?>';
var FORM_KEY = '<?php echo $this->getFormKey() ?>';
</script>