<?php 
/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the Academic Free License (AFL 3.0)
  * You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
  * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/afl-3.0.php
  *
  * @category    Ced
  * @package     Ced_Productfaq
  * @author   CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
  */
?>
<script type="text/javascript">

//<![CDATA[
           var id=1;
var firstStepTemplate = '<div id="group_fields7" class="fieldset fieldset-wide">'+
'<table cellspacing="0" class="form-list">'+
  '<tbody>'+
  '<tr><button style="float:right;margin-bottom:10px" onclick="" class="scalable delete delete-product-option " type="button" title="Delete Option" id="id_1ce635a2716510c3c30a473664c09bc9"><span><span><span>Delete Option</span></span></span></button></tr>'+
    '<tr>'+
      '<td class="label"><label for="title">Title/Question</label></td>'+
      '<td class="value">'+
      '<input type="text" class="input-text"  name="title[quest{{id}}]title" id="title"></td>'+
      '<td class="scope-label"><span class="nobr">[STORE VIEW]</span></td>'+
    '</tr>'+
    '<tr>'+
      '<td class="label"><label for="description">Answer</label></td>'+
      '<td class="value">'+
      '<textarea cols="15" rows="2" class="textarea" name="description[desc{{id}}]description" id="description">Enter description here...</textarea></td>'+
      '<td class="scope-label"><span class="nobr">[STORE VIEW]</span></td>'+
    '</tr>'+
  '</tbody>'+
'</table>'+
'</div>';
      
var productOption = { 
    div : $('product_questions_container_top'),
    templateSyntax : /(^|.|\r|\n)({{(\w+)}})/,
    templateText : firstStepTemplate,
    itemCount : 1,
    add : function(data) { 
        this.template = new Template(this.templateText, this.templateSyntax);

        if(!data.id){
            data = {};
            data.id  = this.itemCount;
            data.type = '';
            data.option_id = 0;
        } else {
            this.itemCount = data.item_count;
        }
       
        Element.insert(this.div, {'after':this.template.evaluate(data)});
        this.id++;
        this.itemCount++;
        this.bindRemoveButtons();
       
    },
    remove : function(event){
    	
        var element = $(Event.findElement(event, 'div'));
        console.log(element);
        if(element){
            element.addClassName('no-display');
            element.addClassName('ignore-validate');
            element.hide();
        }
    },
    bindRemoveButtons : function(){
        var buttons = $$('div.product-related-questions .delete-product-option');
        for(var i=0;i<buttons.length;i++){
            if(!$(buttons[i]).binded){
                $(buttons[i]).binded = true;
                Event.observe(buttons[i], 'click', this.remove.bind(this));
            }
        }
        var inputs = $$('div.product-related-questions', 'div.product-related-questions', 'div.product-related-questions select', 'div.product-related-questions textarea');
        
    }
}




if($('option_panel')){
    $('option_panel').remove();
}

productOption.bindRemoveButtons();


    Event.observe('add_new_defined_question', 'click', productOption.add.bind(productOption));

//]]>
</script>

