<?php
/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the Academic Free License (AFL 3.0)
  * You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
  * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/afl-3.0.php
  *
  * @category    Ced
  * @package     Ced_CsProduct
  * @author   CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
  */
?>
<div class="wrapper-popup">
    <div class="middle" id="anchor-content">
        <div id="page:main-container">
        <?php if($this->getChildHtml('left')): ?>
            <div class="columns <?php echo $this->getContainerCssClass() ?>" id="page:container">
                <div id="page:left" class="side-col">
                    <?php echo $this->getChildHtml('left') ?>
                </div>
                <div class="main-col" id="content">
                    <div class="main-col-inner">
                        <div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
                        <?php echo $this->getChildHtml('content') ?>
                    </div>
                </div>
            </div>
      <?php else: ?>
          <div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
          <?php echo $this->getChildHtml('content') ?>
      <?php endif; ?>
         </div>
    </div>
    <?php if($this->getChildHtml('footer')): ?>
    <div class="footer">
        <?php echo $this->getChildHtml('footer') ?>
    </div>
    <?php endif; ?>
    <?php echo $this->getChildHtml('js') ?>
    <?php echo $this->getChildHtml('profiler') ?>
</div>
