<?php 
 /**
* CedCommerce
*
* NOTICE OF LICENSE
*
* This source file is subject to the Academic Free License (AFL 3.0)
* You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/afl-3.0.php
*
* @category    Ced
* @package     Ced_CsProductfaq
* @author      CedCommerce Core Team <connect@cedcommerce.com >
* @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
* @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/  
?>
<div class="entry-edit product questions product-related-questions">
    <div id="dynamic-price-warrning" style="display:none">
        <ul class="messages">
            <li class="error-msg">
                <ul>
                    <li><?php echo $this->__('Bundle with dynamic pricing cannot include custom defined options. Options will not be saved.') ?></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Product Related Question') ?></h4>
        <div class="right"><?php echo $this->getAddButtonHtml() ?></div>
    </div>

    <div id="product_question_container" class="boxes">
        <div id="product_questions_container_top"></div>
        <?php echo $this->getOptionsBoxHtml() ?>
    </div>
</div>


