<?php 
 /**
  * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the Academic Free License (AFL 3.0)
  * You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
  * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/afl-3.0.php
  *
  * @category    Ced
  * @package     Ced_CsDeal
  * @author      CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
  */
?>

<?php if(!empty($tabs)): ?>
	<div class="block-content panel-body">				
		<div id="accordion" class="tabs panel-group">
			<?php $i=0;$count=count($tabs);?>
			<?php foreach ($tabs as $_tab): ?>
			<?php $i++;?>
			<?php if (!$this->canShowTab($_tab)): continue;  endif; ?>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title">
							<a title="<?php echo $this->getTabUrl($_tab) ?>" id="<?php echo $this->getTabId($_tab) ?>" href="#collapse<?php echo $i ?>" data-parent="#accordion" data-toggle="collapse" aria-expanded="false" class="collapsed tab-item-link <?php echo $this->getTabClass($_tab) ?><?php if (preg_match('/\s?ajax\s?/', $_tab->getClass())) {?> notloaded<?php }?>" name="ajaxupdate<?php echo $i ?>">
								<span></i><span class="changed" title="<?php echo $this->__('The information in this tab has been changed.') ?>"></span><span class="error" title="<?php echo $this->__('This tab contains invalid data. Please solve the problem before saving.') ?>"></span><?php echo $this->getTabLabel($_tab); ?></span>
							</a>
						</h4>
					</div>
					<div id="collapse<?php echo $i ?>" class="panel-collapse collapse in" aria-expanded="true" >
							<div class="panel-body" id="ajaxupdate<?php echo $i ?>">
								<?php echo $this->getTabContent($_tab) ?>
							</div>
					</div>
				</div>
			<?php endforeach; ?>
		</div>
	</div>
<?php endif; ?>

<script type="text/javascript">
    <?php echo $this->getJsObjectName() ?> = new varienTabs('accordion', '', '<?php echo $this->getActiveTabId() ?>', '<?php echo $this->getAllShadowTabs()?>' );

</script> 
