<?php 
  /**
  * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the Academic Free License (AFL 3.0)
  * You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
  * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/afl-3.0.php
  *
  * @category    Ced
  * @package     Ced_CsDeal
  * @author      CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
  */

$product=$this->getProduct();
Mage::helper('csdeal')->initDeal($product);
Mage::helper('csdeal')->isModuleEnable();
Mage::helper('csdeal')->ShowTimer();
Mage::helper('csdeal')->ShowDeal();
list($fyear,$fmonth,$fday,$fhour,$fminute,$fsecond)=explode('-',date('Y-m-d-h-i-s',strtotime(Mage::helper('csdeal')->getDealEnd($product->getId()))));
if(Mage::helper('csdeal')->canShowDeal($product->getId()))
{
    
?>
<!-- Timer start here-->
<?php if(Mage::helper('csdeal')->ShowTimer()) { ?>   
<div class="deal-wrapper">    
<div id="counter-wrapper-<?php echo $this->getProduct()->getId(); ?>" ></div>
<div class="clear" style="clear:both;"></div>
<div class='message-deal'>

<?php 
$dealText=Mage::helper('csdeal')->getDealText();
?>
<span ><?php echo Mage::helper('csdeal')->__($dealText); ?></span>
</div>
</div>
<?php $timeremain = strtotime(Mage::helper('csdeal')->getDealEnd($product->getId()))-strtotime(date("Y-m-d H:i:s", Mage::getModel("core/date")->timestamp(time()))) ; ?>
<?php $productId=$this->getProduct()->getId(); ?>
<script type="text/javascript">
var iDiv = document.createElement('div');
iDiv.id = 'counter-<?php echo $this->getProduct()->getId(); ?>';
iDiv.className = 'counter';
document.getElementById('counter-wrapper-<?php echo $this->getProduct()->getId(); ?>').appendChild(iDiv);
var second<?php echo $productId; ?>= '<?php echo $timeremain; ?>';
var seconds<?php echo $productId; ?> = parseInt(second<?php echo $productId; ?>);
if( seconds<?php echo $productId; ?> != 0){
function secondPassed<?php echo $productId; ?>() {
 var day<?php echo $productId; ?> = Math.floor(seconds<?php echo $productId; ?> / 86400);
 var hour<?php echo $productId; ?> = Math.floor((seconds<?php echo $productId; ?> % 86400)/3600);
    var minutes<?php echo $productId; ?> = Math.floor((seconds<?php echo $productId; ?> % 3600)/60);
    var remainingSeconds<?php echo $productId; ?> = seconds<?php echo $productId; ?> % 60;
 
 if(hour<?php echo $productId; ?> < 10){
  hour<?php echo $productId; ?> = "0" + hour<?php echo $productId; ?>;
 }
 if(minutes<?php echo $productId; ?> < 10){
  minutes<?php echo $productId; ?> = "0" + minutes<?php echo $productId; ?>; 
 }
    if (remainingSeconds<?php echo $productId; ?> < 10) {
        remainingSeconds<?php echo $productId; ?> = "0" + remainingSeconds<?php echo $productId; ?>;  
    }

    document.getElementById('counter-<?php echo $this->getProduct()->getId(); ?>').innerHTML="<ul><li><span class='head-time'> Day </span>"+day<?php echo $this->getProduct()->getId(); ?>+"</span></li><li><span class='head-time'>Hour</span>"+hour<?php echo $this->getProduct()->getId(); ?>+"</li><li> <span class='head-time'> Min </span> "+minutes<?php echo $this->getProduct()->getId(); ?>+"</li><li><span class='head-time'> Sec </span>"+remainingSeconds<?php echo $this->getProduct()->getId(); ?>+"</li><div class='clear' style='clear:both;'></div>";
    if (seconds<?php echo $productId; ?> == 0) {
        clearInterval(countdownTimer<?php echo $productId; ?>);
        dealexpire<?php echo $productId; ?>();
   } else {
        seconds<?php echo $productId; ?>--;
    }

}
var countdownTimer<?php echo $productId; ?> = setInterval('secondPassed<?php echo $productId; ?>()', 1000);
}
function dealexpire<?php echo $productId; ?>(){
       new Ajax.Request("<?php echo   $this->getUrl('csdeal/deal/expire') ?>", {
           method: 'Post',
           parameters: {"product_id":'<?php echo $productId; ?>'},
           onComplete: function(transport) {
           }
       });
   }
</script>
<?php } ?>

<?php } ?>
<?php  echo $this->getChildHtml('child'.$productId); ?>
