<div class="footer-column">
    <h4>CUSTOMER SERVICE</h4>
    <ul class="footer-list">
        <li><a href="#">Delivery</a></li>
        <li><a href="#">Returns</a></li>
        <li><a href="#">Size Guide</a></li>
        <li><a href="#">Happy customers</a></li>
        <li><a href="#">Contact us</a></li>
    </ul>
</div>
<div class="footer-column">
    <h4>ABOUT US</h4>
    <ul class="footer-list">
        <li><a href="#">About us</a></li>
        <li><a href="#">Press</a></li>
        <li><a href="#">Stockists</a></li>
        <li><a href="#">Careers</a></li>
        <li><a href="https://www.thebonniemob.com/wholesales/customer/account/login/">Wholesale</a></li>
    </ul>
</div>