<div class="main_container">
    <div class="col-sm-12" style="margin: 8px 0; padding-left: 8px; padding-right: 8px;">
        <div class="footer-menu-last"><span> The bonniemob is a UK clothing brand that creates beautiful baby clothes, baby gifts and children's clothing. We make high quality, long lasting, fun, colourful designs that are comfortable &amp; that kids love to wear. We are knitwear &amp; jerseywear specialists using organic cottons wherever possible &amp; we pride ourselves on ethical trading and our customer service. Here's some feedback from happy customers:</span></div>
    </div>
    <!--<p><img style="max-width: 100%; margin-top: 20px;" alt="" src="{{media url="wysiwyg/milano/footer-top.jpg"}}" /></p>-->
    <div class="needhelp">
        <p style="text-align: center;"><span style="font-size: medium;"> <br> </span></p>
        <p style="text-align: center;"><span style="font-size: medium;"> <strong> <span style="text-align: center;">NEED HELP? </span> </strong> </span></p>
        <p style="text-align: center;"><strong> <span style="font-size: medium;"> <span style="text-align: center;"> CALL CUSTOMER CARE <span style="color: #000000;">8228 -2818(mon-fri,9AM-5PM)</span> </span>
                    <span style="text-align: center;">OR EMAIL US </span>
                    <a style="font-size: 1.0em;" href="#">sales@bonniebabyasia.com</a> </span> </strong></p>
    </div>
</div>