<?php
/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the Academic Free License (AFL 3.0)
  * You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
  * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/afl-3.0.php
  *
  * @category    Ced
  * @package     Ced_CsProduct
  * @author   CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
  */
?>
<?php if ($this->isReadonly()):?>
<?php $_readonly = ' disabled="disabled" ';?>
<?php else: ?>
<?php $_readonly = '';?>
<?php endif; ?>
<div class="entry-edit">
     <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('catalog')->__('Inventory') ?></h4>  
     </div>
        <ul id="inventory" class="form-list fieldset fieldset-wide">
       <li class="wide">
            <label class="label"><label for="inventory_manage_stock"><?php echo Mage::helper('catalog')->__('Manage Stock') ?></label></label>
            <div style="clear:both"></div>	
            <div class="input-box">
            	<select  id="inventory_manage_stock" name="<?php echo $this->getFieldSuffix() ?>[stock_data][manage_stock]" class="select" <?php echo $_readonly;?>>
                	<option value="1"><?php echo Mage::helper('catalog')->__('Yes') ?></option>
                	<option value="0"<?php if ($this->getConfigFieldValue('manage_stock') == 0): ?> selected="selected"<?php endif; ?>><?php echo Mage::helper('catalog')->__('No') ?></option>
            	</select>
            </div>
            <label class="value scope-label"><?php echo Mage::helper('catalog')->__('[GLOBAL]') ?></label>
            <div style="clear:both"></div>
       </li>

<?php if(!$this->getProduct()->isComposite()): ?>
        <li class="wide">
            <label class="label"><label for="inventory_qty"><?php echo Mage::helper('catalog')->__('Qty') ?><span class="required">*</span></label></label>
            <div style="clear:both"></div>	
            <div class="input-box">
                <?php if (!$_readonly):?>
                <input type="hidden" id="original_inventory_qty" name="<?php echo $this->getFieldSuffix() ?>[stock_data][original_inventory_qty]" value="<?php echo $this->getFieldValue('qty')*1 ?>"/>
                <?php endif;?>
                <input  type="text" class="input-text required-entry validate-number" id="inventory_qty" name="<?php echo $this->getFieldSuffix() ?>[stock_data][qty]" value="<?php echo $this->getFieldValue('qty')*1 ?>" <?php echo $_readonly;?>/>
                </div>
                <label class="value scope-label"><?php echo Mage::helper('catalog')->__('[GLOBAL]') ?></label>
            	<div style="clear:both"></div>
        </li>

        <li class="wide">
            <label class="label"><label for="inventory_min_qty"><?php echo Mage::helper('catalog')->__('Qty for Item\'s Status to become Out of Stock') ?></label></label>
            <div style="clear:both"></div>	
            <div class="input-box">
            <input  type="text" class="input-text validate-number" id="inventory_min_qty" name="<?php echo $this->getFieldSuffix() ?>[stock_data][min_qty]" value="<?php echo $this->getFieldValue('min_qty')*1 ?>" <?php echo $_readonly;?>/>
            </div>
            <label class="value scope-label"><?php echo Mage::helper('catalog')->__('[GLOBAL]') ?></label>
            <div style="clear:both"></div>
			</li>

        <li class="wide">
            <label class="label"><label for="inventory_min_sale_qty"><?php echo Mage::helper('catalog')->__('Minimum Qty Allowed in Shopping Cart') ?></label></label>
            <div style="clear:both"></div>	
            <div class="input-box">
            <input  type="text" class="input-text validate-number" id="inventory_min_sale_qty" name="<?php echo $this->getFieldSuffix() ?>[stock_data][min_sale_qty]" value="<?php echo $this->getFieldValue('min_sale_qty')*1 ?>" <?php echo $_readonly;?>/>
            </div>
            <label class="value scope-label"><?php echo Mage::helper('catalog')->__('[GLOBAL]') ?></label>
            <div style="clear:both"></div>
        </li>
        

        <li class="wide">
            <label class="label"><label for="inventory_max_sale_qty"><?php echo Mage::helper('catalog')->__('Maximum Qty Allowed in Shopping Cart') ?></label></label>
            <div style="clear:both"></div>	
            <div class="input-box">
            <input  type="text" class="input-text validate-number" id="inventory_max_sale_qty" name="<?php echo $this->getFieldSuffix() ?>[stock_data][max_sale_qty]" value="<?php echo $this->getFieldValue('max_sale_qty')*1 ?>" <?php echo $_readonly;?> />
            </div>
            <label class="value scope-label"><?php echo Mage::helper('catalog')->__('[GLOBAL]') ?></label>
            <div style="clear:both"></div>
        </li>

        <?php if($this->canUseQtyDecimals()): ?>
        <li class="wide">
            <label class="label"><label for="inventory_is_qty_decimal"><?php echo Mage::helper('catalog')->__('Qty Uses Decimals') ?></label></label>
            <div style="clear:both"></div>	
            <div class="input-box">
            <select  id="inventory_is_qty_decimal" name="<?php echo $this->getFieldSuffix() ?>[stock_data][is_qty_decimal]" class="select" <?php echo $_readonly;?>>
                <option value="0"><?php echo Mage::helper('catalog')->__('No') ?></option>
                <option value="1"<?php if($this->getFieldValue('is_qty_decimal')==1): ?> selected="selected"<?php endif; ?>><?php echo Mage::helper('catalog')->__('Yes') ?></option>
            </select>
            </div>
            <label class="value scope-label"><?php echo Mage::helper('catalog')->__('[GLOBAL]') ?></label>
            <div style="clear:both"></div>
        </li>
        <?php endif; ?>

        <li class="wide">
            <label class="label"><label for="inventory_backorders"><?php echo Mage::helper('catalog')->__('Backorders') ?></label></label>
            <div style="clear:both"></div>	
            <div class="input-box">
	            <select  id="inventory_backorders" name="<?php echo $this->getFieldSuffix() ?>[stock_data][backorders]" class="select" <?php echo $_readonly;?>>
	            <?php foreach ($this->getBackordersOption() as $option): ?>
	                <?php $_selected = ($option['value'] == $this->getFieldValue('backorders')) ? 'selected="selected"' : '' ?>
	                <option value="<?php echo $option['value'] ?>" <?php echo $_selected ?>><?php echo $option['label'] ?></option>
	            <?php endforeach; ?>
	            </select>
          	</div>
          	<label class="value scope-label"><?php echo Mage::helper('catalog')->__('[GLOBAL]') ?></label>
            <div style="clear:both"></div>
        </li>
        <li class="wide">
            <label class="label"><label for="inventory_notify_stock_qty"><?php echo Mage::helper('catalog')->__('Notify for Quantity Below') ?></label></label>
            <div style="clear:both"></div>	
            <div class="input-box">
            <input  type="text" class="input-text validate-number" id="inventory_notify_stock_qty" name="<?php echo $this->getFieldSuffix() ?>[stock_data][notify_stock_qty]" value="<?php echo $this->getFieldValue('notify_stock_qty')*1 ?>" <?php echo $_readonly;?>/>
            </div>
            <label class="value scope-label"><?php echo Mage::helper('catalog')->__('[GLOBAL]') ?></label>
            <div style="clear:both"></div>
        </li>
<?php endif; ?>
        <li class="wide">
            <label class="label"><label for="inventory_enable_qty_increments"><?php echo Mage::helper('catalog')->__('Enable Qty Increments') ?></label></label>
            <div style="clear:both"></div>	
            <div class="input-box">
            <select  id="inventory_enable_qty_increments" name="<?php echo $this->getFieldSuffix() ?>[stock_data][enable_qty_increments]" class="select" <?php echo $_readonly;?>>
                <option value="1"><?php echo Mage::helper('catalog')->__('Yes') ?></option>
                <option value="0"<?php if ($this->getConfigFieldValue('enable_qty_increments') == 0): ?> selected="selected"<?php endif; ?>><?php echo Mage::helper('catalog')->__('No') ?></option>
            </select>
            <input type="hidden" id="inventory_enable_qty_increments_default" value="<?php echo $this->getDefaultConfigValue('enable_qty_increments'); ?>" />
           	</div>
           	<label class="value scope-label"><?php echo Mage::helper('catalog')->__('[GLOBAL]') ?></label>
            <div style="clear:both"></div>
        </li>
        <li class="wide">
            <label class="label"><label for="inventory_qty_increments"><?php echo Mage::helper('catalog')->__('Qty Increments') ?></label></label>
            <div style="clear:both"></div>	
            <div class="input-box">
                <input type="text" class="input-text validate-digits" id="inventory_qty_increments" name="<?php echo $this->getFieldSuffix() ?>[stock_data][qty_increments]" value="<?php echo $this->getFieldValue('qty_increments')*1 ?>" <?php echo $_readonly;?>/>
            </div>
            <label class="value scope-label"><?php echo Mage::helper('catalog')->__('[GLOBAL]') ?></label>
            <div style="clear:both"></div>		            
        </li>
        <li class="wide">
            <label class="label"><label for="inventory_stock_availability"><?php echo Mage::helper('catalog')->__('Stock Availability') ?></label></label>
            <div style="clear:both"></div>	
            <div class="input-box">
            	<select id="inventory_stock_availability" name="<?php echo $this->getFieldSuffix() ?>[stock_data][is_in_stock]" class="select" <?php echo $_readonly;?>>
            	<?php foreach ($this->getStockOption() as $option): ?>
                <?php $_selected = ($option['value'] == $this->getFieldValue('is_in_stock')) ? 'selected="selected"' : '' ?>
                <option value="<?php echo $option['value'] ?>" <?php echo $_selected ?>><?php echo $option['label'] ?></option>
            	<?php endforeach; ?>
            	</select>
            </div>
            	<label class="value scope-label"><?php echo Mage::helper('catalog')->__('[GLOBAL]') ?></label>
            	<div style="clear:both"></div>
            
        </li>
        </ul>
    <script type="text/javascript">
    //<![CDATA[
    var cataloginventoryNotManagestockFields = {
        inventory_min_sale_qty: true,
        inventory_max_sale_qty: true
    };
    function changeManageStockOption()
    {
        $$('#inventory li').each(manageStockEach);
        return true;
    }
    function manageStockEach(el)
    {
        var manageStock = $('inventory_manage_stock').value;
        if (el == $('inventory_manage_stock').up(1)) {
            return;
        }
        for(field in cataloginventoryNotManagestockFields) {
            if ($(field) && ($(field).up(1) == el)) {
                return;
            }
        }
        if (manageStock == 1) {
            el.show();
        }
        else {
            el.hide();
        }
        return;
    }
    Event.observe($('inventory_manage_stock'), 'change', changeManageStockOption);
    changeManageStockOption();

    function applyEnableQtyIncrements() {
        var enableQtyIncrements = $('inventory_enable_qty_increments').value;
        if (enableQtyIncrements == 1) {
            $('inventory_qty_increments').up('li').show();
        } else {
            $('inventory_qty_increments').up('li').hide();
        }
    }
    Event.observe($('inventory_enable_qty_increments'), 'change', applyEnableQtyIncrements);
    applyEnableQtyIncrements();
    //]]>
    </script>
    </fieldset>
</div>
