<?php
$_social_config = Mage::getStoreConfig('milanoconfig/social');
?>




<div class="footer-container">
    <div class="footer-menu-container">
        <div class="f-left footer-left">
            <div class="footer-menu">
                <?php echo $this->getChildHtml('home_callout_footer'); ?>
                <?php echo $this->getChildHtml('cosmetic_footer_menu'); ?>

            </div>
        </div>
        <div class="follow-us">
            <p>
                <a title="Facebook" href="https://www.facebook.com/TheBonniemob">1</a>
                <a title="Twitter" href="https://twitter.com/thebonniemob">3</a>
                <a title="Instagram" href="https://instagram.com/bonniemob">4</a>
                <a title="Pinterest" href="https://www.pinterest.com/thebonniemob/">6</a>
            </p>
            <p><img style="max-width: 100%;" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>wysiwyg/milano/payments.png" /></p>
        </div>

        <div class="clear">&nbsp;</div>
    </div>
</div>
<div class="footer-last-container">
    <div class="footer-last">
        <div class="f-left">
            <?php echo $this->getChildHtml('cms_footer_links'); ?>
            <?php echo $this->getChildHtml('footer_links'); ?>
        </div>
        <div class="f-right"><?php echo $this->getCopyright(); ?></div>
    </div>
</div>
