<div id="top"></div>
<div class="header-container">



    <div class="header-small-container">
        <div class="header">
            <div class="header-left">
                <?php echo $this->getChildHtml('store_switcher') ?>
                <?php echo $this->getChildHtml('store_language') ?>
                <?php echo $this->getChildHtml('currency') ?>
                <div class="cms-header-links">
                    <div class="header">
                        <div class="header-left">
                            <div class="cms-header-links"><?php echo $this->getChildHtml('cms_header_links') ?></div>
                        </div>
                        <div class="header-right"><span class="welcome-msg"><?php echo $this->getWelcome() ?></span></div>
                    </div>
                </div>
            </div>
            <div class="header-right">&nbsp;</div>
        </div>
    </div>



    <div class="header-main-container">
        <div class="header">
            <?php echo $this->getChildHtml('header_vendor_logo') ?>

            <span class="grow-up"><?php echo $this->__('Bonnie baby has grown up!'); ?></span>
            <div class="header-left header-menu"><?php echo $this->getChildHtml('header_menu') ?></div>
            <div class="header-right">
                <?php echo $this->getChildHtml('top_cart') ?>
                <?php echo $this->getChildHtml('top_compare') ?>
                <?php echo $this->getChildHtml('topLinks') ?>
                <div class="header-menu mobile"><?php echo $this->getChildHtml('header_menu') ?></div>
                <?php echo $this->getChildHtml('topSearch') ?>
            </div>
        </div>
    </div>




    <?php echo $this->getChildHtml('topMenu'); ?>

    <div class="header-promo-container">
        <div class="header">
            <?php echo $this->getChildHtml('header_promo') ?>
        </div>
    </div>
    <?php echo $this->getChildHtml('topBread'); ?>
    <?php echo $this->getChildHtml('topContainer'); ?>
</div>